fastlane_version "1.111.0"

default_platform :ios

platform :ios do
  before_all do
    # ensure_git_status_clean
  end

  desc "Runs all the tests"
  lane :test do
    scan(device: "iPhone 7 (10.1)")
  end
end
